-- Market reference data: classification schemes, groups, memberships, countries.
-- GENERATED from muffin-ui's authored constants (features/markets/classification.ts
-- + taxonomy.ts) by scratchpad/gen-reference-sql.ts — see muffin-deployment README.
--
-- TWO DIFFERENT CONFLICT RULES ON PURPOSE:
--   * schemes/groups/countries use `do update` — names, colours and ETF proxies are
--     app presentation, and the app should win on redeploy.
--   * memberships use `do nothing` — which country sits in which group is REFERENCE
--     DATA meant to be corrected in Supabase Studio (MSCI is accurate; FTSE and World
--     Bank are a best-effort starting point). A redeploy must not silently revert an
--     edit. To force a reset, delete the rows for that scheme/lens first.

create table if not exists market.classification_schemes (
  id                text primary key,
  name              text not null,
  blurb             text,
  lens_region_label text not null default 'Region',
  lens_tier_label   text not null default 'Market tier',
  sort_order        integer not null default 0
);

create table if not exists market.classification_groups (
  scheme_id  text not null references market.classification_schemes (id) on delete cascade,
  lens       text not null check (lens in ('region', 'tier')),
  id         text not null,
  name       text not null,
  short      text,
  color      text,
  etf        text,
  sort_order integer not null default 0,
  primary key (scheme_id, lens, id)
);

-- One row per (scheme, lens, country). Materialised rather than derived: MSCI's tier
-- is a function of its region while FTSE's is its own list, and the app only ever asks
-- "which group is this ISO in, for this scheme+lens".
create table if not exists market.classification_members (
  scheme_id text not null,
  lens      text not null,
  iso2      text not null,
  group_id  text not null,
  primary key (scheme_id, lens, iso2),
  foreign key (scheme_id, lens, group_id)
    references market.classification_groups (scheme_id, lens, id) on delete cascade
);

create index if not exists classification_members_group_idx
  on market.classification_members (scheme_id, lens, group_id);

create table if not exists market.countries (
  iso2       text primary key,
  name       text not null,
  flag       text,
  region_id  text,
  market     text check (market in ('developed', 'emerging')),
  -- Single-country ETF used as the equity-market proxy for performance.
  etf_symbol text,
  -- True when the app has a country page for it (the 19 modelled countries).
  drillable  boolean not null default false
);

create table if not exists market.regions (
  id         text primary key,
  name       text not null,
  icon       text,
  blurb      text,
  sort_order integer not null default 0
);

-- === Seed: schemes =========================================================
insert into market.classification_schemes (id, name, blurb, lens_region_label, lens_tier_label, sort_order) values
  ('msci', 'MSCI', 'iShares / BlackRock benchmark — Developed · Emerging · Frontier.', 'Region', 'Market tier', 1),
  ('ftse', 'FTSE', 'Vanguard benchmark — Korea & Poland Developed; advanced/secondary EM.', 'Region', 'Market tier', 2),
  ('world-bank', 'World Bank', 'Macro view — 7 geographic regions and income groups (all economies).', 'Region', 'Income group', 3)
on conflict (id) do update set name = excluded.name, blurb = excluded.blurb,
  lens_region_label = excluded.lens_region_label, lens_tier_label = excluded.lens_tier_label,
  sort_order = excluded.sort_order;

-- === Seed: groups ==========================================================
insert into market.classification_groups (scheme_id, lens, id, name, short, color, etf, sort_order) values
  ('msci', 'region', 'na', 'North America', 'N. America', '#875DAE', 'IVV', 1),
  ('msci', 'region', 'dev-europe', 'Developed Europe', 'Dev Europe', '#6E63A6', 'IEUR', 2),
  ('msci', 'region', 'dev-pacific', 'Developed Pacific', 'Dev Pacific', '#E9A94D', 'EPP', 3),
  ('msci', 'region', 'em-asia', 'Emerging Asia', 'EM Asia', '#C0577B', 'EEMA', 4),
  ('msci', 'region', 'em-emea', 'Emerging EMEA', 'EM EMEA', '#D98E3A', 'EEM', 5),
  ('msci', 'region', 'em-latam', 'Latin America', 'LatAm', '#7FB35C', 'ILF', 6),
  ('msci', 'region', 'frontier', 'Frontier', 'Frontier', '#9BC97C', 'FM', 7),
  ('msci', 'tier', 'developed', 'Developed', 'Developed', '#875DAE', 'URTH', 1),
  ('msci', 'tier', 'emerging', 'Emerging', 'Emerging', '#E9A94D', 'EEM', 2),
  ('msci', 'tier', 'frontier', 'Frontier', 'Frontier', '#7FB35C', 'FM', 3),
  ('ftse', 'region', 'na', 'North America', 'N. America', '#875DAE', 'IVV', 1),
  ('ftse', 'region', 'dev-europe', 'Developed Europe', 'Dev Europe', '#6E63A6', 'IEUR', 2),
  ('ftse', 'region', 'dev-pacific', 'Developed Pacific', 'Dev Pacific', '#E9A94D', 'EPP', 3),
  ('ftse', 'region', 'em-asia', 'Emerging Asia', 'EM Asia', '#C0577B', 'EEMA', 4),
  ('ftse', 'region', 'em-emea', 'Emerging EMEA', 'EM EMEA', '#D98E3A', 'EEM', 5),
  ('ftse', 'region', 'em-latam', 'Latin America', 'LatAm', '#7FB35C', 'ILF', 6),
  ('ftse', 'region', 'frontier', 'Frontier', 'Frontier', '#9BC97C', 'FM', 7),
  ('ftse', 'tier', 'developed', 'Developed', 'Developed', '#875DAE', 'VEA', 1),
  ('ftse', 'tier', 'advanced-emerging', 'Advanced Emerging', 'Adv EM', '#E9A94D', 'VWO', 2),
  ('ftse', 'tier', 'secondary-emerging', 'Secondary Emerging', 'Sec EM', '#D98E3A', 'VWO', 3),
  ('ftse', 'tier', 'frontier', 'Frontier', 'Frontier', '#7FB35C', 'FM', 4),
  ('world-bank', 'region', 'north-america', 'North America', 'N. America', '#875DAE', null, 1),
  ('world-bank', 'region', 'latin-america-caribbean', 'Latin America & Caribbean', 'LAC', '#7FB35C', null, 2),
  ('world-bank', 'region', 'europe-central-asia', 'Europe & Central Asia', 'ECA', '#6E63A6', null, 3),
  ('world-bank', 'region', 'middle-east-north-africa', 'Middle East & N. Africa', 'MENA', '#D98E3A', null, 4),
  ('world-bank', 'region', 'sub-saharan-africa', 'Sub-Saharan Africa', 'SSA', '#5B9AA8', null, 5),
  ('world-bank', 'region', 'south-asia', 'South Asia', 'S. Asia', '#C0577B', null, 6),
  ('world-bank', 'region', 'east-asia-pacific', 'East Asia & Pacific', 'EAP', '#E9A94D', null, 7),
  ('world-bank', 'tier', 'high', 'High income', 'High', '#875DAE', null, 1),
  ('world-bank', 'tier', 'upper-middle', 'Upper-middle income', 'Upper-mid', '#C2A4DC', null, 2),
  ('world-bank', 'tier', 'lower-middle', 'Lower-middle income', 'Lower-mid', '#E9A94D', null, 3),
  ('world-bank', 'tier', 'low', 'Low income', 'Low', '#D98E3A', null, 4)
on conflict (scheme_id, lens, id) do update set name = excluded.name, short = excluded.short,
  color = excluded.color, etf = excluded.etf, sort_order = excluded.sort_order;

-- === Seed: memberships (do nothing on conflict — editable reference data) ===
insert into market.classification_members (scheme_id, lens, iso2, group_id) values
  ('msci', 'region', 'CA', 'na'),
  ('msci', 'region', 'US', 'na'),
  ('msci', 'region', 'ID', 'em-asia'),
  ('msci', 'region', 'AU', 'dev-pacific'),
  ('msci', 'region', 'CN', 'em-asia'),
  ('msci', 'region', 'ES', 'dev-europe'),
  ('msci', 'region', 'BR', 'em-latam'),
  ('msci', 'region', 'PH', 'em-asia'),
  ('msci', 'region', 'CL', 'em-latam'),
  ('msci', 'region', 'MX', 'em-latam'),
  ('msci', 'region', 'IT', 'dev-europe'),
  ('msci', 'region', 'IN', 'em-asia'),
  ('msci', 'region', 'NO', 'dev-europe'),
  ('msci', 'region', 'KZ', 'frontier'),
  ('msci', 'region', 'TR', 'em-emea'),
  ('msci', 'region', 'NZ', 'dev-pacific'),
  ('msci', 'region', 'JP', 'dev-pacific'),
  ('msci', 'region', 'CO', 'em-latam'),
  ('msci', 'region', 'MY', 'em-asia'),
  ('msci', 'region', 'ZA', 'em-emea'),
  ('msci', 'region', 'GR', 'em-emea'),
  ('msci', 'region', 'FR', 'dev-europe'),
  ('msci', 'region', 'GB', 'dev-europe'),
  ('msci', 'region', 'OM', 'frontier'),
  ('msci', 'region', 'PE', 'em-latam'),
  ('msci', 'region', 'SA', 'em-emea'),
  ('msci', 'region', 'PK', 'frontier'),
  ('msci', 'region', 'TH', 'em-asia'),
  ('msci', 'region', 'MA', 'frontier'),
  ('msci', 'region', 'DE', 'dev-europe'),
  ('msci', 'region', 'NG', 'frontier'),
  ('msci', 'region', 'MU', 'frontier'),
  ('msci', 'region', 'RS', 'frontier'),
  ('msci', 'region', 'PL', 'em-emea'),
  ('msci', 'region', 'CI', 'frontier'),
  ('msci', 'region', 'VN', 'frontier'),
  ('msci', 'region', 'RO', 'frontier'),
  ('msci', 'region', 'EG', 'em-emea'),
  ('msci', 'region', 'SN', 'frontier'),
  ('msci', 'region', 'HR', 'frontier'),
  ('msci', 'region', 'DK', 'dev-europe'),
  ('msci', 'region', 'SE', 'dev-europe'),
  ('msci', 'region', 'KE', 'frontier'),
  ('msci', 'region', 'FI', 'dev-europe'),
  ('msci', 'region', 'AT', 'dev-europe'),
  ('msci', 'region', 'BD', 'frontier'),
  ('msci', 'region', 'CZ', 'em-emea'),
  ('msci', 'region', 'PT', 'dev-europe'),
  ('msci', 'region', 'TN', 'frontier'),
  ('msci', 'region', 'HU', 'em-emea'),
  ('msci', 'region', 'IL', 'dev-europe'),
  ('msci', 'region', 'CH', 'dev-europe'),
  ('msci', 'region', 'AE', 'em-emea'),
  ('msci', 'region', 'IS', 'frontier'),
  ('msci', 'region', 'KR', 'em-asia'),
  ('msci', 'region', 'LT', 'frontier'),
  ('msci', 'region', 'JO', 'frontier'),
  ('msci', 'region', 'SI', 'frontier'),
  ('msci', 'region', 'BE', 'dev-europe'),
  ('msci', 'region', 'BH', 'frontier'),
  ('msci', 'region', 'NL', 'dev-europe'),
  ('msci', 'region', 'IE', 'dev-europe'),
  ('msci', 'region', 'LK', 'frontier'),
  ('msci', 'region', 'QA', 'em-emea'),
  ('msci', 'region', 'KW', 'em-emea'),
  ('msci', 'region', 'TW', 'em-asia'),
  ('msci', 'region', 'HK', 'dev-pacific'),
  ('msci', 'tier', 'CA', 'developed'),
  ('msci', 'tier', 'US', 'developed'),
  ('msci', 'tier', 'ID', 'emerging'),
  ('msci', 'tier', 'AU', 'developed'),
  ('msci', 'tier', 'CN', 'emerging'),
  ('msci', 'tier', 'ES', 'developed'),
  ('msci', 'tier', 'BR', 'emerging'),
  ('msci', 'tier', 'PH', 'emerging'),
  ('msci', 'tier', 'CL', 'emerging'),
  ('msci', 'tier', 'MX', 'emerging'),
  ('msci', 'tier', 'IT', 'developed'),
  ('msci', 'tier', 'IN', 'emerging'),
  ('msci', 'tier', 'NO', 'developed'),
  ('msci', 'tier', 'KZ', 'frontier'),
  ('msci', 'tier', 'TR', 'emerging'),
  ('msci', 'tier', 'NZ', 'developed'),
  ('msci', 'tier', 'JP', 'developed'),
  ('msci', 'tier', 'CO', 'emerging'),
  ('msci', 'tier', 'MY', 'emerging'),
  ('msci', 'tier', 'ZA', 'emerging'),
  ('msci', 'tier', 'GR', 'emerging'),
  ('msci', 'tier', 'FR', 'developed'),
  ('msci', 'tier', 'GB', 'developed'),
  ('msci', 'tier', 'OM', 'frontier'),
  ('msci', 'tier', 'PE', 'emerging'),
  ('msci', 'tier', 'SA', 'emerging'),
  ('msci', 'tier', 'PK', 'frontier'),
  ('msci', 'tier', 'TH', 'emerging'),
  ('msci', 'tier', 'MA', 'frontier'),
  ('msci', 'tier', 'DE', 'developed'),
  ('msci', 'tier', 'NG', 'frontier'),
  ('msci', 'tier', 'MU', 'frontier'),
  ('msci', 'tier', 'RS', 'frontier'),
  ('msci', 'tier', 'PL', 'emerging'),
  ('msci', 'tier', 'CI', 'frontier'),
  ('msci', 'tier', 'VN', 'frontier'),
  ('msci', 'tier', 'RO', 'frontier'),
  ('msci', 'tier', 'EG', 'emerging'),
  ('msci', 'tier', 'SN', 'frontier'),
  ('msci', 'tier', 'HR', 'frontier'),
  ('msci', 'tier', 'DK', 'developed'),
  ('msci', 'tier', 'SE', 'developed'),
  ('msci', 'tier', 'KE', 'frontier'),
  ('msci', 'tier', 'FI', 'developed'),
  ('msci', 'tier', 'AT', 'developed'),
  ('msci', 'tier', 'BD', 'frontier'),
  ('msci', 'tier', 'CZ', 'emerging'),
  ('msci', 'tier', 'PT', 'developed'),
  ('msci', 'tier', 'TN', 'frontier'),
  ('msci', 'tier', 'HU', 'emerging'),
  ('msci', 'tier', 'IL', 'developed'),
  ('msci', 'tier', 'CH', 'developed'),
  ('msci', 'tier', 'AE', 'emerging'),
  ('msci', 'tier', 'IS', 'frontier'),
  ('msci', 'tier', 'KR', 'emerging'),
  ('msci', 'tier', 'LT', 'frontier'),
  ('msci', 'tier', 'JO', 'frontier'),
  ('msci', 'tier', 'SI', 'frontier'),
  ('msci', 'tier', 'BE', 'developed'),
  ('msci', 'tier', 'BH', 'frontier'),
  ('msci', 'tier', 'NL', 'developed'),
  ('msci', 'tier', 'IE', 'developed'),
  ('msci', 'tier', 'LK', 'frontier'),
  ('msci', 'tier', 'QA', 'emerging'),
  ('msci', 'tier', 'KW', 'emerging'),
  ('msci', 'tier', 'TW', 'emerging'),
  ('msci', 'tier', 'HK', 'developed'),
  ('ftse', 'region', 'CA', 'na'),
  ('ftse', 'region', 'US', 'na'),
  ('ftse', 'region', 'ID', 'em-asia'),
  ('ftse', 'region', 'AU', 'dev-pacific'),
  ('ftse', 'region', 'CN', 'em-asia'),
  ('ftse', 'region', 'ES', 'dev-europe'),
  ('ftse', 'region', 'BR', 'em-latam'),
  ('ftse', 'region', 'PH', 'em-asia'),
  ('ftse', 'region', 'CL', 'em-latam'),
  ('ftse', 'region', 'MX', 'em-latam'),
  ('ftse', 'region', 'IT', 'dev-europe'),
  ('ftse', 'region', 'IN', 'em-asia'),
  ('ftse', 'region', 'NO', 'dev-europe'),
  ('ftse', 'region', 'KZ', 'frontier'),
  ('ftse', 'region', 'TR', 'em-emea'),
  ('ftse', 'region', 'NZ', 'dev-pacific'),
  ('ftse', 'region', 'JP', 'dev-pacific'),
  ('ftse', 'region', 'CO', 'em-latam'),
  ('ftse', 'region', 'MY', 'em-asia'),
  ('ftse', 'region', 'ZA', 'em-emea'),
  ('ftse', 'region', 'GR', 'em-emea'),
  ('ftse', 'region', 'FR', 'dev-europe'),
  ('ftse', 'region', 'GB', 'dev-europe'),
  ('ftse', 'region', 'OM', 'frontier'),
  ('ftse', 'region', 'PE', 'em-latam'),
  ('ftse', 'region', 'SA', 'em-emea'),
  ('ftse', 'region', 'PK', 'em-asia'),
  ('ftse', 'region', 'TH', 'em-asia'),
  ('ftse', 'region', 'MA', 'frontier'),
  ('ftse', 'region', 'DE', 'dev-europe'),
  ('ftse', 'region', 'NG', 'frontier'),
  ('ftse', 'region', 'MU', 'frontier'),
  ('ftse', 'region', 'RS', 'frontier'),
  ('ftse', 'region', 'PL', 'dev-europe'),
  ('ftse', 'region', 'CI', 'frontier'),
  ('ftse', 'region', 'VN', 'frontier'),
  ('ftse', 'region', 'RO', 'frontier'),
  ('ftse', 'region', 'EG', 'em-emea'),
  ('ftse', 'region', 'SN', 'frontier'),
  ('ftse', 'region', 'HR', 'frontier'),
  ('ftse', 'region', 'DK', 'dev-europe'),
  ('ftse', 'region', 'SE', 'dev-europe'),
  ('ftse', 'region', 'KE', 'frontier'),
  ('ftse', 'region', 'FI', 'dev-europe'),
  ('ftse', 'region', 'AT', 'dev-europe'),
  ('ftse', 'region', 'BD', 'frontier'),
  ('ftse', 'region', 'CZ', 'em-emea'),
  ('ftse', 'region', 'PT', 'dev-europe'),
  ('ftse', 'region', 'TN', 'frontier'),
  ('ftse', 'region', 'HU', 'em-emea'),
  ('ftse', 'region', 'IL', 'dev-europe'),
  ('ftse', 'region', 'CH', 'dev-europe'),
  ('ftse', 'region', 'AE', 'em-emea'),
  ('ftse', 'region', 'IS', 'frontier'),
  ('ftse', 'region', 'KR', 'dev-pacific'),
  ('ftse', 'region', 'JO', 'frontier'),
  ('ftse', 'region', 'SI', 'frontier'),
  ('ftse', 'region', 'BE', 'dev-europe'),
  ('ftse', 'region', 'BH', 'frontier'),
  ('ftse', 'region', 'NL', 'dev-europe'),
  ('ftse', 'region', 'IE', 'dev-europe'),
  ('ftse', 'region', 'LK', 'frontier'),
  ('ftse', 'region', 'QA', 'em-emea'),
  ('ftse', 'region', 'KW', 'em-emea'),
  ('ftse', 'region', 'TW', 'em-asia'),
  ('ftse', 'region', 'HK', 'dev-pacific'),
  ('ftse', 'tier', 'CA', 'developed'),
  ('ftse', 'tier', 'US', 'developed'),
  ('ftse', 'tier', 'ID', 'secondary-emerging'),
  ('ftse', 'tier', 'AU', 'developed'),
  ('ftse', 'tier', 'CN', 'secondary-emerging'),
  ('ftse', 'tier', 'ES', 'developed'),
  ('ftse', 'tier', 'BR', 'advanced-emerging'),
  ('ftse', 'tier', 'PH', 'secondary-emerging'),
  ('ftse', 'tier', 'CL', 'secondary-emerging'),
  ('ftse', 'tier', 'MX', 'advanced-emerging'),
  ('ftse', 'tier', 'IT', 'developed'),
  ('ftse', 'tier', 'IN', 'secondary-emerging'),
  ('ftse', 'tier', 'NO', 'developed'),
  ('ftse', 'tier', 'KZ', 'frontier'),
  ('ftse', 'tier', 'TR', 'advanced-emerging'),
  ('ftse', 'tier', 'NZ', 'developed'),
  ('ftse', 'tier', 'JP', 'developed'),
  ('ftse', 'tier', 'CO', 'secondary-emerging'),
  ('ftse', 'tier', 'MY', 'advanced-emerging'),
  ('ftse', 'tier', 'ZA', 'advanced-emerging'),
  ('ftse', 'tier', 'GR', 'advanced-emerging'),
  ('ftse', 'tier', 'FR', 'developed'),
  ('ftse', 'tier', 'GB', 'developed'),
  ('ftse', 'tier', 'OM', 'frontier'),
  ('ftse', 'tier', 'SA', 'secondary-emerging'),
  ('ftse', 'tier', 'PK', 'secondary-emerging'),
  ('ftse', 'tier', 'TH', 'advanced-emerging'),
  ('ftse', 'tier', 'MA', 'frontier'),
  ('ftse', 'tier', 'DE', 'developed'),
  ('ftse', 'tier', 'NG', 'frontier'),
  ('ftse', 'tier', 'MU', 'frontier'),
  ('ftse', 'tier', 'RS', 'frontier'),
  ('ftse', 'tier', 'PL', 'developed'),
  ('ftse', 'tier', 'CI', 'frontier'),
  ('ftse', 'tier', 'VN', 'frontier'),
  ('ftse', 'tier', 'RO', 'secondary-emerging'),
  ('ftse', 'tier', 'EG', 'secondary-emerging'),
  ('ftse', 'tier', 'SN', 'frontier'),
  ('ftse', 'tier', 'HR', 'frontier'),
  ('ftse', 'tier', 'DK', 'developed'),
  ('ftse', 'tier', 'SE', 'developed'),
  ('ftse', 'tier', 'KE', 'frontier'),
  ('ftse', 'tier', 'FI', 'developed'),
  ('ftse', 'tier', 'AT', 'developed'),
  ('ftse', 'tier', 'BD', 'frontier'),
  ('ftse', 'tier', 'CZ', 'advanced-emerging'),
  ('ftse', 'tier', 'PT', 'developed'),
  ('ftse', 'tier', 'TN', 'frontier'),
  ('ftse', 'tier', 'HU', 'advanced-emerging'),
  ('ftse', 'tier', 'IL', 'developed'),
  ('ftse', 'tier', 'CH', 'developed'),
  ('ftse', 'tier', 'AE', 'secondary-emerging'),
  ('ftse', 'tier', 'IS', 'frontier'),
  ('ftse', 'tier', 'KR', 'developed'),
  ('ftse', 'tier', 'JO', 'frontier'),
  ('ftse', 'tier', 'SI', 'frontier'),
  ('ftse', 'tier', 'BE', 'developed'),
  ('ftse', 'tier', 'BH', 'frontier'),
  ('ftse', 'tier', 'NL', 'developed'),
  ('ftse', 'tier', 'IE', 'developed'),
  ('ftse', 'tier', 'LK', 'frontier'),
  ('ftse', 'tier', 'QA', 'secondary-emerging'),
  ('ftse', 'tier', 'KW', 'secondary-emerging'),
  ('ftse', 'tier', 'TW', 'advanced-emerging'),
  ('ftse', 'tier', 'HK', 'developed'),
  ('world-bank', 'region', 'CA', 'north-america'),
  ('world-bank', 'region', 'RU', 'europe-central-asia'),
  ('world-bank', 'region', 'SB', 'east-asia-pacific'),
  ('world-bank', 'region', 'US', 'north-america'),
  ('world-bank', 'region', 'BS', 'latin-america-caribbean'),
  ('world-bank', 'region', 'VU', 'east-asia-pacific'),
  ('world-bank', 'region', 'FK', 'latin-america-caribbean'),
  ('world-bank', 'region', 'ID', 'east-asia-pacific'),
  ('world-bank', 'region', 'AU', 'east-asia-pacific'),
  ('world-bank', 'region', 'CN', 'east-asia-pacific'),
  ('world-bank', 'region', 'FJ', 'east-asia-pacific'),
  ('world-bank', 'region', 'NC', 'east-asia-pacific'),
  ('world-bank', 'region', 'ES', 'europe-central-asia'),
  ('world-bank', 'region', 'BR', 'latin-america-caribbean'),
  ('world-bank', 'region', 'AR', 'latin-america-caribbean'),
  ('world-bank', 'region', 'PH', 'east-asia-pacific'),
  ('world-bank', 'region', 'PF', 'east-asia-pacific'),
  ('world-bank', 'region', 'CV', 'sub-saharan-africa'),
  ('world-bank', 'region', 'CL', 'latin-america-caribbean'),
  ('world-bank', 'region', 'MX', 'latin-america-caribbean'),
  ('world-bank', 'region', 'IT', 'europe-central-asia'),
  ('world-bank', 'region', 'PG', 'east-asia-pacific'),
  ('world-bank', 'region', 'IN', 'south-asia'),
  ('world-bank', 'region', 'NO', 'europe-central-asia'),
  ('world-bank', 'region', 'GL', 'north-america'),
  ('world-bank', 'region', 'FO', 'europe-central-asia'),
  ('world-bank', 'region', 'CD', 'sub-saharan-africa'),
  ('world-bank', 'region', 'AO', 'sub-saharan-africa'),
  ('world-bank', 'region', 'KZ', 'europe-central-asia'),
  ('world-bank', 'region', 'TR', 'europe-central-asia'),
  ('world-bank', 'region', 'NZ', 'east-asia-pacific'),
  ('world-bank', 'region', 'JP', 'east-asia-pacific'),
  ('world-bank', 'region', 'PR', 'latin-america-caribbean'),
  ('world-bank', 'region', 'CY', 'europe-central-asia'),
  ('world-bank', 'region', 'CO', 'latin-america-caribbean'),
  ('world-bank', 'region', 'MY', 'east-asia-pacific'),
  ('world-bank', 'region', 'UA', 'europe-central-asia'),
  ('world-bank', 'region', 'VE', 'latin-america-caribbean'),
  ('world-bank', 'region', 'ZA', 'sub-saharan-africa'),
  ('world-bank', 'region', 'GR', 'europe-central-asia'),
  ('world-bank', 'region', 'FR', 'europe-central-asia'),
  ('world-bank', 'region', 'TT', 'latin-america-caribbean'),
  ('world-bank', 'region', 'GB', 'europe-central-asia'),
  ('world-bank', 'region', 'OM', 'middle-east-north-africa'),
  ('world-bank', 'region', 'SD', 'sub-saharan-africa'),
  ('world-bank', 'region', 'MZ', 'sub-saharan-africa'),
  ('world-bank', 'region', 'PE', 'latin-america-caribbean'),
  ('world-bank', 'region', 'SA', 'middle-east-north-africa'),
  ('world-bank', 'region', 'ML', 'sub-saharan-africa'),
  ('world-bank', 'region', 'IR', 'middle-east-north-africa'),
  ('world-bank', 'region', 'MN', 'east-asia-pacific'),
  ('world-bank', 'region', 'AZ', 'europe-central-asia'),
  ('world-bank', 'region', 'GN', 'sub-saharan-africa'),
  ('world-bank', 'region', 'MP', 'east-asia-pacific'),
  ('world-bank', 'region', 'MM', 'east-asia-pacific'),
  ('world-bank', 'region', 'AF', 'south-asia'),
  ('world-bank', 'region', 'KM', 'sub-saharan-africa'),
  ('world-bank', 'region', 'ZM', 'sub-saharan-africa'),
  ('world-bank', 'region', 'PK', 'south-asia'),
  ('world-bank', 'region', 'TH', 'east-asia-pacific'),
  ('world-bank', 'region', 'GP', 'latin-america-caribbean'),
  ('world-bank', 'region', 'TZ', 'sub-saharan-africa'),
  ('world-bank', 'region', 'CF', 'sub-saharan-africa'),
  ('world-bank', 'region', 'DZ', 'middle-east-north-africa'),
  ('world-bank', 'region', 'MA', 'middle-east-north-africa'),
  ('world-bank', 'region', 'SS', 'sub-saharan-africa'),
  ('world-bank', 'region', 'CM', 'sub-saharan-africa'),
  ('world-bank', 'region', 'BO', 'latin-america-caribbean'),
  ('world-bank', 'region', 'WS', 'east-asia-pacific'),
  ('world-bank', 'region', 'ET', 'sub-saharan-africa'),
  ('world-bank', 'region', 'DE', 'europe-central-asia'),
  ('world-bank', 'region', 'HN', 'latin-america-caribbean'),
  ('world-bank', 'region', 'TD', 'sub-saharan-africa'),
  ('world-bank', 'region', 'NG', 'sub-saharan-africa'),
  ('world-bank', 'region', 'NE', 'sub-saharan-africa'),
  ('world-bank', 'region', 'LY', 'middle-east-north-africa'),
  ('world-bank', 'region', 'UZ', 'europe-central-asia'),
  ('world-bank', 'region', 'TM', 'europe-central-asia'),
  ('world-bank', 'region', 'PA', 'latin-america-caribbean'),
  ('world-bank', 'region', 'NI', 'latin-america-caribbean'),
  ('world-bank', 'region', 'TO', 'east-asia-pacific'),
  ('world-bank', 'region', 'MG', 'sub-saharan-africa'),
  ('world-bank', 'region', 'CG', 'sub-saharan-africa'),
  ('world-bank', 'region', 'SO', 'sub-saharan-africa'),
  ('world-bank', 'region', 'MU', 'sub-saharan-africa'),
  ('world-bank', 'region', 'RS', 'europe-central-asia'),
  ('world-bank', 'region', 'PL', 'europe-central-asia'),
  ('world-bank', 'region', 'CI', 'sub-saharan-africa'),
  ('world-bank', 'region', 'FM', 'east-asia-pacific'),
  ('world-bank', 'region', 'ST', 'sub-saharan-africa'),
  ('world-bank', 'region', 'YE', 'middle-east-north-africa'),
  ('world-bank', 'region', 'NA', 'sub-saharan-africa'),
  ('world-bank', 'region', 'VN', 'east-asia-pacific'),
  ('world-bank', 'region', 'BY', 'europe-central-asia'),
  ('world-bank', 'region', 'RO', 'europe-central-asia'),
  ('world-bank', 'region', 'KP', 'east-asia-pacific'),
  ('world-bank', 'region', 'EG', 'middle-east-north-africa'),
  ('world-bank', 'region', 'CU', 'latin-america-caribbean'),
  ('world-bank', 'region', 'SN', 'sub-saharan-africa'),
  ('world-bank', 'region', 'TJ', 'europe-central-asia'),
  ('world-bank', 'region', 'HR', 'europe-central-asia'),
  ('world-bank', 'region', 'DK', 'europe-central-asia'),
  ('world-bank', 'region', 'MR', 'sub-saharan-africa'),
  ('world-bank', 'region', 'BW', 'sub-saharan-africa'),
  ('world-bank', 'region', 'SC', 'sub-saharan-africa'),
  ('world-bank', 'region', 'SE', 'europe-central-asia'),
  ('world-bank', 'region', 'BF', 'sub-saharan-africa'),
  ('world-bank', 'region', 'KE', 'sub-saharan-africa'),
  ('world-bank', 'region', 'GY', 'latin-america-caribbean'),
  ('world-bank', 'region', 'MW', 'sub-saharan-africa'),
  ('world-bank', 'region', 'FI', 'europe-central-asia'),
  ('world-bank', 'region', 'AT', 'europe-central-asia'),
  ('world-bank', 'region', 'ZW', 'sub-saharan-africa'),
  ('world-bank', 'region', 'BD', 'south-asia'),
  ('world-bank', 'region', 'CR', 'latin-america-caribbean'),
  ('world-bank', 'region', 'LA', 'east-asia-pacific'),
  ('world-bank', 'region', 'GT', 'latin-america-caribbean'),
  ('world-bank', 'region', 'CZ', 'europe-central-asia'),
  ('world-bank', 'region', 'KG', 'europe-central-asia'),
  ('world-bank', 'region', 'SK', 'europe-central-asia'),
  ('world-bank', 'region', 'PT', 'europe-central-asia'),
  ('world-bank', 'region', 'PY', 'latin-america-caribbean'),
  ('world-bank', 'region', 'EC', 'latin-america-caribbean'),
  ('world-bank', 'region', 'KY', 'latin-america-caribbean'),
  ('world-bank', 'region', 'AG', 'latin-america-caribbean'),
  ('world-bank', 'region', 'TC', 'latin-america-caribbean'),
  ('world-bank', 'region', 'TN', 'middle-east-north-africa'),
  ('world-bank', 'region', 'UG', 'sub-saharan-africa'),
  ('world-bank', 'region', 'GA', 'sub-saharan-africa'),
  ('world-bank', 'region', 'HU', 'europe-central-asia'),
  ('world-bank', 'region', 'IQ', 'middle-east-north-africa'),
  ('world-bank', 'region', 'VI', 'latin-america-caribbean'),
  ('world-bank', 'region', 'ER', 'sub-saharan-africa'),
  ('world-bank', 'region', 'LR', 'sub-saharan-africa'),
  ('world-bank', 'region', 'EH', 'middle-east-north-africa'),
  ('world-bank', 'region', 'BG', 'europe-central-asia'),
  ('world-bank', 'region', 'MT', 'europe-central-asia'),
  ('world-bank', 'region', 'DO', 'latin-america-caribbean'),
  ('world-bank', 'region', 'SR', 'latin-america-caribbean'),
  ('world-bank', 'region', 'SY', 'middle-east-north-africa'),
  ('world-bank', 'region', 'MD', 'europe-central-asia'),
  ('world-bank', 'region', 'GH', 'sub-saharan-africa'),
  ('world-bank', 'region', 'BJ', 'sub-saharan-africa'),
  ('world-bank', 'region', 'RE', 'sub-saharan-africa'),
  ('world-bank', 'region', 'GE', 'europe-central-asia'),
  ('world-bank', 'region', 'IL', 'middle-east-north-africa'),
  ('world-bank', 'region', 'CH', 'europe-central-asia'),
  ('world-bank', 'region', 'NP', 'south-asia'),
  ('world-bank', 'region', 'MQ', 'latin-america-caribbean'),
  ('world-bank', 'region', 'KN', 'latin-america-caribbean'),
  ('world-bank', 'region', 'BA', 'europe-central-asia'),
  ('world-bank', 'region', 'AL', 'europe-central-asia'),
  ('world-bank', 'region', 'LV', 'europe-central-asia'),
  ('world-bank', 'region', 'SL', 'sub-saharan-africa'),
  ('world-bank', 'region', 'UY', 'latin-america-caribbean'),
  ('world-bank', 'region', 'AE', 'middle-east-north-africa'),
  ('world-bank', 'region', 'HT', 'latin-america-caribbean'),
  ('world-bank', 'region', 'XK', 'europe-central-asia'),
  ('world-bank', 'region', 'SV', 'latin-america-caribbean'),
  ('world-bank', 'region', 'IS', 'europe-central-asia'),
  ('world-bank', 'region', 'AS', 'east-asia-pacific'),
  ('world-bank', 'region', 'AM', 'europe-central-asia'),
  ('world-bank', 'region', 'GF', 'latin-america-caribbean'),
  ('world-bank', 'region', 'BZ', 'latin-america-caribbean'),
  ('world-bank', 'region', 'KR', 'east-asia-pacific'),
  ('world-bank', 'region', 'TG', 'sub-saharan-africa'),
  ('world-bank', 'region', 'LT', 'europe-central-asia'),
  ('world-bank', 'region', 'GW', 'sub-saharan-africa'),
  ('world-bank', 'region', 'JO', 'middle-east-north-africa'),
  ('world-bank', 'region', 'ME', 'europe-central-asia'),
  ('world-bank', 'region', 'SI', 'europe-central-asia'),
  ('world-bank', 'region', 'CW', 'latin-america-caribbean'),
  ('world-bank', 'region', 'MK', 'europe-central-asia'),
  ('world-bank', 'region', 'EE', 'europe-central-asia'),
  ('world-bank', 'region', 'KH', 'east-asia-pacific'),
  ('world-bank', 'region', 'BI', 'sub-saharan-africa'),
  ('world-bank', 'region', 'DM', 'latin-america-caribbean'),
  ('world-bank', 'region', 'YT', 'sub-saharan-africa'),
  ('world-bank', 'region', 'GU', 'east-asia-pacific'),
  ('world-bank', 'region', 'BE', 'europe-central-asia'),
  ('world-bank', 'region', 'GM', 'sub-saharan-africa'),
  ('world-bank', 'region', 'DJ', 'middle-east-north-africa'),
  ('world-bank', 'region', 'BH', 'middle-east-north-africa'),
  ('world-bank', 'region', 'NL', 'europe-central-asia'),
  ('world-bank', 'region', 'BT', 'south-asia'),
  ('world-bank', 'region', 'RW', 'sub-saharan-africa'),
  ('world-bank', 'region', 'IE', 'europe-central-asia'),
  ('world-bank', 'region', 'PW', 'east-asia-pacific'),
  ('world-bank', 'region', 'BQBO', 'latin-america-caribbean'),
  ('world-bank', 'region', 'LC', 'latin-america-caribbean'),
  ('world-bank', 'region', 'SZ', 'sub-saharan-africa'),
  ('world-bank', 'region', 'TL', 'east-asia-pacific'),
  ('world-bank', 'region', 'LB', 'middle-east-north-africa'),
  ('world-bank', 'region', 'JM', 'latin-america-caribbean'),
  ('world-bank', 'region', 'LS', 'sub-saharan-africa'),
  ('world-bank', 'region', 'BM', 'north-america'),
  ('world-bank', 'region', 'LK', 'south-asia'),
  ('world-bank', 'region', 'GD', 'latin-america-caribbean'),
  ('world-bank', 'region', 'BB', 'latin-america-caribbean'),
  ('world-bank', 'region', 'VC', 'latin-america-caribbean'),
  ('world-bank', 'region', 'QA', 'middle-east-north-africa'),
  ('world-bank', 'region', 'KW', 'middle-east-north-africa'),
  ('world-bank', 'region', 'PS', 'middle-east-north-africa'),
  ('world-bank', 'region', 'TW', 'east-asia-pacific'),
  ('world-bank', 'region', 'BN', 'east-asia-pacific'),
  ('world-bank', 'region', 'VG', 'latin-america-caribbean'),
  ('world-bank', 'region', 'AW', 'latin-america-caribbean'),
  ('world-bank', 'region', 'LU', 'europe-central-asia'),
  ('world-bank', 'region', 'MS', 'latin-america-caribbean'),
  ('world-bank', 'region', 'GQ', 'sub-saharan-africa'),
  ('world-bank', 'region', 'AI', 'latin-america-caribbean'),
  ('world-bank', 'region', 'MF', 'latin-america-caribbean'),
  ('world-bank', 'region', 'BQSE', 'latin-america-caribbean'),
  ('world-bank', 'region', 'BQSA', 'latin-america-caribbean'),
  ('world-bank', 'region', 'MV', 'south-asia'),
  ('world-bank', 'region', 'TV', 'east-asia-pacific'),
  ('world-bank', 'region', 'NR', 'east-asia-pacific'),
  ('world-bank', 'region', 'SX', 'latin-america-caribbean'),
  ('world-bank', 'region', 'BL', 'latin-america-caribbean'),
  ('world-bank', 'region', 'MH', 'east-asia-pacific'),
  ('world-bank', 'region', 'HK', 'east-asia-pacific'),
  ('world-bank', 'tier', 'CA', 'high'),
  ('world-bank', 'tier', 'RU', 'high'),
  ('world-bank', 'tier', 'SB', 'lower-middle'),
  ('world-bank', 'tier', 'US', 'high'),
  ('world-bank', 'tier', 'BS', 'high'),
  ('world-bank', 'tier', 'VU', 'lower-middle'),
  ('world-bank', 'tier', 'ID', 'upper-middle'),
  ('world-bank', 'tier', 'AU', 'high'),
  ('world-bank', 'tier', 'CN', 'upper-middle'),
  ('world-bank', 'tier', 'FJ', 'upper-middle'),
  ('world-bank', 'tier', 'NC', 'lower-middle'),
  ('world-bank', 'tier', 'ES', 'high'),
  ('world-bank', 'tier', 'BR', 'upper-middle'),
  ('world-bank', 'tier', 'AR', 'upper-middle'),
  ('world-bank', 'tier', 'PH', 'lower-middle'),
  ('world-bank', 'tier', 'PF', 'high'),
  ('world-bank', 'tier', 'CV', 'lower-middle'),
  ('world-bank', 'tier', 'CL', 'high'),
  ('world-bank', 'tier', 'MX', 'upper-middle'),
  ('world-bank', 'tier', 'IT', 'high'),
  ('world-bank', 'tier', 'PG', 'lower-middle'),
  ('world-bank', 'tier', 'IN', 'lower-middle'),
  ('world-bank', 'tier', 'NO', 'high'),
  ('world-bank', 'tier', 'GL', 'high'),
  ('world-bank', 'tier', 'FO', 'high'),
  ('world-bank', 'tier', 'CD', 'low'),
  ('world-bank', 'tier', 'AO', 'lower-middle'),
  ('world-bank', 'tier', 'KZ', 'upper-middle'),
  ('world-bank', 'tier', 'TR', 'upper-middle'),
  ('world-bank', 'tier', 'NZ', 'high'),
  ('world-bank', 'tier', 'JP', 'high'),
  ('world-bank', 'tier', 'PR', 'high'),
  ('world-bank', 'tier', 'CY', 'high'),
  ('world-bank', 'tier', 'CO', 'upper-middle'),
  ('world-bank', 'tier', 'MY', 'upper-middle'),
  ('world-bank', 'tier', 'UA', 'lower-middle'),
  ('world-bank', 'tier', 'VE', 'upper-middle'),
  ('world-bank', 'tier', 'ZA', 'upper-middle'),
  ('world-bank', 'tier', 'GR', 'high'),
  ('world-bank', 'tier', 'FR', 'high'),
  ('world-bank', 'tier', 'TT', 'high'),
  ('world-bank', 'tier', 'GB', 'high'),
  ('world-bank', 'tier', 'OM', 'high'),
  ('world-bank', 'tier', 'SD', 'low'),
  ('world-bank', 'tier', 'MZ', 'low'),
  ('world-bank', 'tier', 'PE', 'upper-middle'),
  ('world-bank', 'tier', 'SA', 'high'),
  ('world-bank', 'tier', 'ML', 'low'),
  ('world-bank', 'tier', 'IR', 'lower-middle'),
  ('world-bank', 'tier', 'MN', 'lower-middle'),
  ('world-bank', 'tier', 'AZ', 'upper-middle'),
  ('world-bank', 'tier', 'GN', 'low'),
  ('world-bank', 'tier', 'MM', 'lower-middle'),
  ('world-bank', 'tier', 'AF', 'low'),
  ('world-bank', 'tier', 'ZM', 'lower-middle'),
  ('world-bank', 'tier', 'PK', 'lower-middle'),
  ('world-bank', 'tier', 'TH', 'upper-middle'),
  ('world-bank', 'tier', 'TZ', 'lower-middle'),
  ('world-bank', 'tier', 'CF', 'low'),
  ('world-bank', 'tier', 'DZ', 'upper-middle'),
  ('world-bank', 'tier', 'MA', 'lower-middle'),
  ('world-bank', 'tier', 'SS', 'low'),
  ('world-bank', 'tier', 'CM', 'lower-middle'),
  ('world-bank', 'tier', 'BO', 'lower-middle'),
  ('world-bank', 'tier', 'WS', 'lower-middle'),
  ('world-bank', 'tier', 'ET', 'low'),
  ('world-bank', 'tier', 'DE', 'high'),
  ('world-bank', 'tier', 'HN', 'lower-middle'),
  ('world-bank', 'tier', 'TD', 'low'),
  ('world-bank', 'tier', 'NG', 'lower-middle'),
  ('world-bank', 'tier', 'NE', 'low'),
  ('world-bank', 'tier', 'LY', 'upper-middle'),
  ('world-bank', 'tier', 'UZ', 'lower-middle'),
  ('world-bank', 'tier', 'TM', 'upper-middle'),
  ('world-bank', 'tier', 'PA', 'high'),
  ('world-bank', 'tier', 'NI', 'lower-middle'),
  ('world-bank', 'tier', 'TO', 'upper-middle'),
  ('world-bank', 'tier', 'MG', 'low'),
  ('world-bank', 'tier', 'CG', 'lower-middle'),
  ('world-bank', 'tier', 'SO', 'low'),
  ('world-bank', 'tier', 'MU', 'upper-middle'),
  ('world-bank', 'tier', 'RS', 'upper-middle'),
  ('world-bank', 'tier', 'PL', 'high'),
  ('world-bank', 'tier', 'CI', 'lower-middle'),
  ('world-bank', 'tier', 'YE', 'low'),
  ('world-bank', 'tier', 'NA', 'upper-middle'),
  ('world-bank', 'tier', 'VN', 'lower-middle'),
  ('world-bank', 'tier', 'BY', 'upper-middle'),
  ('world-bank', 'tier', 'RO', 'high'),
  ('world-bank', 'tier', 'KP', 'low'),
  ('world-bank', 'tier', 'EG', 'lower-middle'),
  ('world-bank', 'tier', 'SN', 'lower-middle'),
  ('world-bank', 'tier', 'TJ', 'lower-middle'),
  ('world-bank', 'tier', 'HR', 'high'),
  ('world-bank', 'tier', 'DK', 'high'),
  ('world-bank', 'tier', 'MR', 'lower-middle'),
  ('world-bank', 'tier', 'BW', 'upper-middle'),
  ('world-bank', 'tier', 'SE', 'high'),
  ('world-bank', 'tier', 'BF', 'low'),
  ('world-bank', 'tier', 'KE', 'lower-middle'),
  ('world-bank', 'tier', 'MW', 'low'),
  ('world-bank', 'tier', 'FI', 'high'),
  ('world-bank', 'tier', 'AT', 'high'),
  ('world-bank', 'tier', 'ZW', 'lower-middle'),
  ('world-bank', 'tier', 'BD', 'lower-middle'),
  ('world-bank', 'tier', 'CR', 'upper-middle'),
  ('world-bank', 'tier', 'LA', 'lower-middle'),
  ('world-bank', 'tier', 'GT', 'upper-middle'),
  ('world-bank', 'tier', 'CZ', 'high'),
  ('world-bank', 'tier', 'KG', 'lower-middle'),
  ('world-bank', 'tier', 'SK', 'high'),
  ('world-bank', 'tier', 'PT', 'high'),
  ('world-bank', 'tier', 'PY', 'upper-middle'),
  ('world-bank', 'tier', 'EC', 'upper-middle'),
  ('world-bank', 'tier', 'KY', 'high'),
  ('world-bank', 'tier', 'TN', 'lower-middle'),
  ('world-bank', 'tier', 'UG', 'low'),
  ('world-bank', 'tier', 'GA', 'upper-middle'),
  ('world-bank', 'tier', 'HU', 'high'),
  ('world-bank', 'tier', 'IQ', 'upper-middle'),
  ('world-bank', 'tier', 'ER', 'low'),
  ('world-bank', 'tier', 'LR', 'low'),
  ('world-bank', 'tier', 'MT', 'high'),
  ('world-bank', 'tier', 'DO', 'upper-middle'),
  ('world-bank', 'tier', 'SR', 'upper-middle'),
  ('world-bank', 'tier', 'SY', 'low'),
  ('world-bank', 'tier', 'MD', 'upper-middle'),
  ('world-bank', 'tier', 'GH', 'lower-middle'),
  ('world-bank', 'tier', 'BJ', 'low'),
  ('world-bank', 'tier', 'GE', 'upper-middle'),
  ('world-bank', 'tier', 'IL', 'high'),
  ('world-bank', 'tier', 'CH', 'high'),
  ('world-bank', 'tier', 'NP', 'lower-middle'),
  ('world-bank', 'tier', 'BA', 'upper-middle'),
  ('world-bank', 'tier', 'AL', 'upper-middle'),
  ('world-bank', 'tier', 'LV', 'high'),
  ('world-bank', 'tier', 'SL', 'low'),
  ('world-bank', 'tier', 'UY', 'high'),
  ('world-bank', 'tier', 'AE', 'high'),
  ('world-bank', 'tier', 'HT', 'lower-middle'),
  ('world-bank', 'tier', 'XK', 'upper-middle'),
  ('world-bank', 'tier', 'SV', 'lower-middle'),
  ('world-bank', 'tier', 'IS', 'high'),
  ('world-bank', 'tier', 'AM', 'upper-middle'),
  ('world-bank', 'tier', 'BZ', 'upper-middle'),
  ('world-bank', 'tier', 'KR', 'high'),
  ('world-bank', 'tier', 'TG', 'low'),
  ('world-bank', 'tier', 'LT', 'high'),
  ('world-bank', 'tier', 'GW', 'low'),
  ('world-bank', 'tier', 'JO', 'upper-middle'),
  ('world-bank', 'tier', 'ME', 'upper-middle'),
  ('world-bank', 'tier', 'SI', 'high'),
  ('world-bank', 'tier', 'CW', 'high'),
  ('world-bank', 'tier', 'MK', 'upper-middle'),
  ('world-bank', 'tier', 'EE', 'high'),
  ('world-bank', 'tier', 'KH', 'lower-middle'),
  ('world-bank', 'tier', 'BI', 'low'),
  ('world-bank', 'tier', 'GU', 'high'),
  ('world-bank', 'tier', 'BE', 'high'),
  ('world-bank', 'tier', 'GM', 'low'),
  ('world-bank', 'tier', 'DJ', 'lower-middle'),
  ('world-bank', 'tier', 'BH', 'high'),
  ('world-bank', 'tier', 'NL', 'high'),
  ('world-bank', 'tier', 'BT', 'lower-middle'),
  ('world-bank', 'tier', 'RW', 'low'),
  ('world-bank', 'tier', 'IE', 'high'),
  ('world-bank', 'tier', 'TL', 'lower-middle'),
  ('world-bank', 'tier', 'LB', 'upper-middle'),
  ('world-bank', 'tier', 'JM', 'upper-middle'),
  ('world-bank', 'tier', 'BM', 'high'),
  ('world-bank', 'tier', 'LK', 'lower-middle'),
  ('world-bank', 'tier', 'GD', 'upper-middle'),
  ('world-bank', 'tier', 'BB', 'high'),
  ('world-bank', 'tier', 'QA', 'high'),
  ('world-bank', 'tier', 'KW', 'high'),
  ('world-bank', 'tier', 'PS', 'upper-middle'),
  ('world-bank', 'tier', 'TW', 'high'),
  ('world-bank', 'tier', 'AW', 'high'),
  ('world-bank', 'tier', 'LU', 'high'),
  ('world-bank', 'tier', 'MV', 'upper-middle'),
  ('world-bank', 'tier', 'HK', 'high')
on conflict (scheme_id, lens, iso2) do nothing;

-- === Seed: regions =========================================================
insert into market.regions (id, name, icon, blurb, sort_order) values
  ('north-america', 'North America', 'region-na', 'Deep, liquid developed markets led by US mega-caps.', 1),
  ('europe', 'Europe', 'region-eu', 'Diversified developed markets, value & industrials tilt.', 2),
  ('asia-pacific', 'Asia-Pacific', 'region-apac', 'Japan, Australia and fast-growing emerging Asia.', 3),
  ('greater-china', 'Greater China', 'region-china', 'China, Hong Kong and Taiwan — policy-sensitive.', 4),
  ('latin-america', 'Latin America', 'region-latam', 'Commodity-rich emerging markets, higher beta.', 5),
  ('mea', 'Middle East & Africa', 'region-mea', 'Energy exporters and frontier growth stories.', 6)
on conflict (id) do update set name = excluded.name, icon = excluded.icon,
  blurb = excluded.blurb, sort_order = excluded.sort_order;

-- === Seed: countries =======================================================
-- Every ISO in world-geo.ts gets a row (so the globe can name any country);
-- `drillable` marks the ones with a country page, `etf_symbol` the ones with a
-- performance proxy.
insert into market.countries (iso2, name, flag, region_id, market, etf_symbol, drillable) values
  ('CA', 'Canada', '🇨🇦', 'north-america', 'developed', 'EWC', true),
  ('RU', 'Russian Federation', null, null, null, null, false),
  ('SB', 'Solomon Islands', null, null, null, null, false),
  ('US', 'United States', '🇺🇸', 'north-america', 'developed', 'IVV', true),
  ('BS', 'Bahamas', null, null, null, null, false),
  ('VU', 'Vanuatu', null, null, null, null, false),
  ('FK', 'Falkland Islands', null, null, null, null, false),
  ('ID', 'Indonesia', null, null, null, null, false),
  ('AU', 'Australia', '🇦🇺', 'asia-pacific', 'developed', 'EWA', true),
  ('CN', 'China', '🇨🇳', 'greater-china', 'emerging', 'MCHI', true),
  ('FJ', 'Fiji', null, null, null, null, false),
  ('NC', 'New Caledonia', null, null, null, null, false),
  ('ES', 'Spain', null, null, null, null, false),
  ('BR', 'Brazil', '🇧🇷', 'latin-america', 'emerging', 'EWZ', true),
  ('AR', 'Argentina', null, null, null, null, false),
  ('PH', 'Philippines', null, null, null, null, false),
  ('PF', 'French Polynesia', null, null, null, null, false),
  ('CV', 'Cape Verde', null, null, null, null, false),
  ('CL', 'Chile', '🇨🇱', 'latin-america', 'emerging', 'ECH', true),
  ('MX', 'Mexico', '🇲🇽', 'north-america', 'emerging', 'EWW', true),
  ('IT', 'Italy', null, null, null, null, false),
  ('PG', 'Papua New Guinea', null, null, null, null, false),
  ('IN', 'India', '🇮🇳', 'asia-pacific', 'emerging', 'INDA', true),
  ('NO', 'Norway', null, null, null, null, false),
  ('GL', 'Greenland', null, null, null, null, false),
  ('FO', 'Faeroe Islands', null, null, null, null, false),
  ('CD', 'Democratic Republic of the Congo', null, null, null, null, false),
  ('AO', 'Angola', null, null, null, null, false),
  ('KZ', 'Kazakhstan', null, null, null, null, false),
  ('TR', 'Turkey', null, null, null, null, false),
  ('NZ', 'New Zealand', null, null, null, null, false),
  ('JP', 'Japan', '🇯🇵', 'asia-pacific', 'developed', 'EWJ', true),
  ('PR', 'Puerto Rico', null, null, null, null, false),
  ('CY', 'Cyprus', null, null, null, null, false),
  ('CO', 'Colombia', null, null, null, null, false),
  ('MY', 'Malaysia', null, null, null, null, false),
  ('UA', 'Ukraine', null, null, null, null, false),
  ('VE', 'Venezuela', null, null, null, null, false),
  ('ZA', 'South Africa', '🇿🇦', 'mea', 'emerging', 'EZA', true),
  ('GR', 'Greece', null, null, null, null, false),
  ('FR', 'France', '🇫🇷', 'europe', 'developed', 'EWQ', true),
  ('TT', 'Trinidad and Tobago', null, null, null, null, false),
  ('GB', 'United Kingdom', '🇬🇧', 'europe', 'developed', 'EWU', true),
  ('OM', 'Oman', null, null, null, null, false),
  ('SD', 'Sudan', null, null, null, null, false),
  ('MZ', 'Mozambique', null, null, null, null, false),
  ('PE', 'Peru', null, null, null, null, false),
  ('SA', 'Saudi Arabia', '🇸🇦', 'mea', 'emerging', 'KSA', true),
  ('ML', 'Mali', null, null, null, null, false),
  ('IR', 'Iran', null, null, null, null, false),
  ('MN', 'Mongolia', null, null, null, null, false),
  ('AZ', 'Azerbaijan', null, null, null, null, false),
  ('GN', 'Guinea', null, null, null, null, false),
  ('MP', 'Northern Mariana Islands', null, null, null, null, false),
  ('MM', 'Myanmar', null, null, null, null, false),
  ('AF', 'Afghanistan', null, null, null, null, false),
  ('KM', 'Comoros', null, null, null, null, false),
  ('ZM', 'Zambia', null, null, null, null, false),
  ('PK', 'Pakistan', null, null, null, null, false),
  ('TH', 'Thailand', null, null, null, null, false),
  ('GP', 'Guadeloupe', null, null, null, null, false),
  ('TZ', 'Tanzania', null, null, null, null, false),
  ('CF', 'Central African Republic', null, null, null, null, false),
  ('DZ', 'Algeria', null, null, null, null, false),
  ('MA', 'Morocco', null, null, null, null, false),
  ('SS', 'South Sudan', null, null, null, null, false),
  ('CM', 'Cameroon', null, null, null, null, false),
  ('BO', 'Bolivia', null, null, null, null, false),
  ('WS', 'Samoa', null, null, null, null, false),
  ('ET', 'Ethiopia', null, null, null, null, false),
  ('DE', 'Germany', '🇩🇪', 'europe', 'developed', 'EWG', true),
  ('HN', 'Honduras', null, null, null, null, false),
  ('TD', 'Chad', null, null, null, null, false),
  ('NG', 'Nigeria', null, null, null, null, false),
  ('NE', 'Niger', null, null, null, null, false),
  ('LY', 'Libya', null, null, null, null, false),
  ('UZ', 'Uzbekistan', null, null, null, null, false),
  ('TM', 'Turkmenistan', null, null, null, null, false),
  ('PA', 'Panama', null, null, null, null, false),
  ('NI', 'Nicaragua', null, null, null, null, false),
  ('TO', 'Tonga', null, null, null, null, false),
  ('MG', 'Madagascar', null, null, null, null, false),
  ('CG', 'Republic of Congo', null, null, null, null, false),
  ('SO', 'Somalia', null, null, null, null, false),
  ('MU', 'Mauritius', null, null, null, null, false),
  ('RS', 'Serbia', null, null, null, null, false),
  ('PL', 'Poland', null, null, null, null, false),
  ('CI', 'Côte d''Ivoire', null, null, null, null, false),
  ('FM', 'Federated States of Micronesia', null, null, null, null, false),
  ('ST', 'São Tomé and Principe', null, null, null, null, false),
  ('YE', 'Yemen', null, null, null, null, false),
  ('NA', 'Namibia', null, null, null, null, false),
  ('VN', 'Vietnam', null, null, null, null, false),
  ('BY', 'Belarus', null, null, null, null, false),
  ('RO', 'Romania', null, null, null, null, false),
  ('KP', 'Dem. Rep. Korea', null, null, null, null, false),
  ('EG', 'Egypt', null, null, null, null, false),
  ('CU', 'Cuba', null, null, null, null, false),
  ('SN', 'Senegal', null, null, null, null, false),
  ('TJ', 'Tajikistan', null, null, null, null, false),
  ('HR', 'Croatia', null, null, null, null, false),
  ('DK', 'Denmark', null, null, null, null, false),
  ('MR', 'Mauritania', null, null, null, null, false),
  ('BW', 'Botswana', null, null, null, null, false),
  ('SC', 'Seychelles', null, null, null, null, false),
  ('SE', 'Sweden', null, null, null, null, false),
  ('BF', 'Burkina Faso', null, null, null, null, false),
  ('KE', 'Kenya', null, null, null, null, false),
  ('GY', 'Guyana', null, null, null, null, false),
  ('MW', 'Malawi', null, null, null, null, false),
  ('FI', 'Finland', null, null, null, null, false),
  ('AT', 'Austria', null, null, null, null, false),
  ('ZW', 'Zimbabwe', null, null, null, null, false),
  ('BD', 'Bangladesh', null, null, null, null, false),
  ('CR', 'Costa Rica', null, null, null, null, false),
  ('LA', 'Lao PDR', null, null, null, null, false),
  ('GT', 'Guatemala', null, null, null, null, false),
  ('CZ', 'Czech Republic', null, null, null, null, false),
  ('KG', 'Kyrgyzstan', null, null, null, null, false),
  ('SK', 'Slovakia', null, null, null, null, false),
  ('PT', 'Portugal', null, null, null, null, false),
  ('PY', 'Paraguay', null, null, null, null, false),
  ('EC', 'Ecuador', null, null, null, null, false),
  ('KY', 'Cayman Islands', null, null, null, null, false),
  ('AG', 'Antigua and Barbuda', null, null, null, null, false),
  ('TC', 'Turks and Caicos Islands', null, null, null, null, false),
  ('TN', 'Tunisia', null, null, null, null, false),
  ('UG', 'Uganda', null, null, null, null, false),
  ('GA', 'Gabon', null, null, null, null, false),
  ('HU', 'Hungary', null, null, null, null, false),
  ('IQ', 'Iraq', null, null, null, null, false),
  ('VI', 'United States Virgin Islands', null, null, null, null, false),
  ('ER', 'Eritrea', null, null, null, null, false),
  ('LR', 'Liberia', null, null, null, null, false),
  ('EH', 'Western Sahara', null, null, null, null, false),
  ('BG', 'Bulgaria', null, null, null, null, false),
  ('MT', 'Malta', null, null, null, null, false),
  ('DO', 'Dominican Republic', null, null, null, null, false),
  ('SR', 'Suriname', null, null, null, null, false),
  ('SY', 'Syria', null, null, null, null, false),
  ('MD', 'Moldova', null, null, null, null, false),
  ('GH', 'Ghana', null, null, null, null, false),
  ('BJ', 'Benin', null, null, null, null, false),
  ('RE', 'Reunion', null, null, null, null, false),
  ('GE', 'Georgia', null, null, null, null, false),
  ('IL', 'Israel', null, null, null, null, false),
  ('CH', 'Switzerland', '🇨🇭', 'europe', 'developed', 'EWL', true),
  ('NP', 'Nepal', null, null, null, null, false),
  ('MQ', 'Martinique', null, null, null, null, false),
  ('KN', 'Saint Kitts and Nevis', null, null, null, null, false),
  ('BA', 'Bosnia and Herzegovina', null, null, null, null, false),
  ('AL', 'Albania', null, null, null, null, false),
  ('LV', 'Latvia', null, null, null, null, false),
  ('SL', 'Sierra Leone', null, null, null, null, false),
  ('UY', 'Uruguay', null, null, null, null, false),
  ('AE', 'United Arab Emirates', '🇦🇪', 'mea', 'emerging', 'UAE', true),
  ('HT', 'Haiti', null, null, null, null, false),
  ('XK', 'Kosovo', null, null, null, null, false),
  ('SV', 'El Salvador', null, null, null, null, false),
  ('IS', 'Iceland', null, null, null, null, false),
  ('AS', 'American Samoa', null, null, null, null, false),
  ('AM', 'Armenia', null, null, null, null, false),
  ('GF', 'French Guiana', null, null, null, null, false),
  ('BZ', 'Belize', null, null, null, null, false),
  ('KR', 'South Korea', '🇰🇷', 'asia-pacific', 'emerging', 'EWY', true),
  ('TG', 'Togo', null, null, null, null, false),
  ('LT', 'Lithuania', null, null, null, null, false),
  ('GW', 'Guinea-Bissau', null, null, null, null, false),
  ('JO', 'Jordan', null, null, null, null, false),
  ('ME', 'Montenegro', null, null, null, null, false),
  ('SI', 'Slovenia', null, null, null, null, false),
  ('CW', 'Curaçao', null, null, null, null, false),
  ('MK', 'Macedonia', null, null, null, null, false),
  ('EE', 'Estonia', null, null, null, null, false),
  ('KH', 'Cambodia', null, null, null, null, false),
  ('BI', 'Burundi', null, null, null, null, false),
  ('DM', 'Dominica', null, null, null, null, false),
  ('YT', 'Mayotte', null, null, null, null, false),
  ('GU', 'Guam', null, null, null, null, false),
  ('BE', 'Belgium', null, null, null, null, false),
  ('GM', 'The Gambia', null, null, null, null, false),
  ('DJ', 'Djibouti', null, null, null, null, false),
  ('BH', 'Bahrain', null, null, null, null, false),
  ('NL', 'Netherlands', null, null, null, null, false),
  ('BT', 'Bhutan', null, null, null, null, false),
  ('RW', 'Rwanda', null, null, null, null, false),
  ('IE', 'Ireland', null, null, null, null, false),
  ('PW', 'Palau', null, null, null, null, false),
  ('BQBO', 'Netherlands', null, null, null, null, false),
  ('LC', 'Saint Lucia', null, null, null, null, false),
  ('SZ', 'Swaziland', null, null, null, null, false),
  ('TL', 'Timor-Leste', null, null, null, null, false),
  ('LB', 'Lebanon', null, null, null, null, false),
  ('JM', 'Jamaica', null, null, null, null, false),
  ('LS', 'Lesotho', null, null, null, null, false),
  ('BM', 'Bermuda', null, null, null, null, false),
  ('LK', 'Sri Lanka', null, null, null, null, false),
  ('GD', 'Grenada', null, null, null, null, false),
  ('BB', 'Barbados', null, null, null, null, false),
  ('VC', 'Saint Vincent and the Grenadines', null, null, null, null, false),
  ('QA', 'Qatar', null, null, null, null, false),
  ('KW', 'Kuwait', null, null, null, null, false),
  ('PS', 'Palestine', null, null, null, null, false),
  ('TW', 'Taiwan', '🇹🇼', 'greater-china', 'emerging', 'EWT', true),
  ('BN', 'Brunei Darussalam', null, null, null, null, false),
  ('VG', 'British Virgin Islands', null, null, null, null, false),
  ('AW', 'Aruba', null, null, null, null, false),
  ('LU', 'Luxembourg', null, null, null, null, false),
  ('MS', 'Montserrat', null, null, null, null, false),
  ('GQ', 'Equatorial Guinea', null, null, null, null, false),
  ('AI', 'Anguilla', null, null, null, null, false),
  ('MF', 'Saint-Martin', null, null, null, null, false),
  ('BQSE', 'St. Eustatius (Netherlands)', null, null, null, null, false),
  ('BQSA', 'Saba (Netherlands)', null, null, null, null, false),
  ('MV', 'Maldives', null, null, null, null, false),
  ('TV', 'Tuvalu', null, null, null, null, false),
  ('NR', 'Nauru', null, null, null, null, false),
  ('SX', 'Sint Maarten', null, null, null, null, false),
  ('BL', 'Saint-Barthélemy', null, null, null, null, false),
  ('MH', 'Marshall Islands', null, null, null, null, false),
  ('HK', 'Hong Kong', '🇭🇰', 'greater-china', 'developed', 'EWH', true)
on conflict (iso2) do update set name = excluded.name, flag = excluded.flag,
  region_id = excluded.region_id, market = excluded.market,
  etf_symbol = excluded.etf_symbol, drillable = excluded.drillable;

-- === Grants ================================================================
grant select on market.classification_schemes, market.classification_groups,
                market.classification_members, market.countries, market.regions
  to anon, authenticated;
grant select, insert, update, delete on market.classification_schemes,
                market.classification_groups, market.classification_members,
                market.countries, market.regions to service_role;

notify pgrst, 'reload schema';
