-- Re-issued because DROPPING A VIEW LOSES ITS ACL. Extracted from `relacl`, so this is
-- what the database actually grants rather than a list of what someone expected.
grant DELETE, INSERT, SELECT, UPDATE on market.backlog_drain to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.country_sector_performance to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.coverage_current to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.data_defect to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.fund_country_weight to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.fund_holding_current to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.fund_holdings to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.fund_sector_weight to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.fx_rate_current to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.instrument_current to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.macro_current to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.metric_out_of_range to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_cn_filings to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_cn_segments to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_corporate_actions to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_daily_history to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_dividends to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_eps_history to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_filing_history to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_filings to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_fundamentals to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_fx_history to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_in_history to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_in_segments to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_industry to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_insider to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_kr_history to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_kr_segments to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_local_symbol to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_management to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_metrics to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_news to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_performance to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_price_history to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_price_targets to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_prices to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_profile to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_profile_detail to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_promotion to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_quarters to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_segment_alias to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_segments to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_share_stats to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_statements to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_symbol_repair to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_ticker to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_ttm to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_wikidata to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_xbrl to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.pending_yahoo_symbol to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.performance to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.price_series to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.resource_health to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.sector_constituents to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.security_currency to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.security_current to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.security_disclosure to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.security_earnings_surprise to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.security_facet_status to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.security_facets to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.security_fundamentals_current to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.security_funds to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.security_industries to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.security_insider_summary to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.security_leadership to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.security_market_cap_usd to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.security_metric_series to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.security_news to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.security_next_earnings to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.security_peers to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.security_ratio_series to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.security_recent_filings to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.security_segment_current to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.security_segment_detail to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.security_segment_geography to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.security_segment_latest to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.security_segment_spine to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.security_statement_current to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.security_style to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.security_symbol to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.symbol_cache_classification to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.symbol_security to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.ticker_disagreement to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.untracked_listing to ingest_rw;
grant DELETE, INSERT, SELECT, UPDATE on market.venue_currency to ingest_rw;
grant SELECT on market.backlog_drain to anon;
grant SELECT on market.backlog_drain to metrics_ro;
grant SELECT on market.backlog_drain to service_role;
grant SELECT on market.fund_country_weight to anon;
grant SELECT on market.fund_country_weight to authenticated;
grant SELECT on market.fund_country_weight to service_role;
grant SELECT on market.fund_holding_current to service_role;
grant SELECT on market.fund_holdings to anon;
grant SELECT on market.fund_holdings to authenticated;
grant SELECT on market.fund_holdings to service_role;
grant SELECT on market.fund_sector_weight to anon;
grant SELECT on market.fund_sector_weight to authenticated;
grant SELECT on market.fund_sector_weight to service_role;
grant SELECT on market.fx_rate_current to anon;
grant SELECT on market.fx_rate_current to authenticated;
grant SELECT on market.fx_rate_current to service_role;
grant SELECT on market.instrument_current to anon;
grant SELECT on market.instrument_current to authenticated;
grant SELECT on market.instrument_current to service_role;
grant SELECT on market.macro_current to anon;
grant SELECT on market.macro_current to authenticated;
grant SELECT on market.macro_current to service_role;
grant SELECT on market.metric_out_of_range to anon;
grant SELECT on market.metric_out_of_range to authenticated;
grant SELECT on market.metric_out_of_range to metrics_ro;
grant SELECT on market.metric_out_of_range to service_role;
grant SELECT on market.pending_cn_filings to service_role;
grant SELECT on market.pending_cn_segments to service_role;
grant SELECT on market.pending_corporate_actions to service_role;
grant SELECT on market.pending_daily_history to service_role;
grant SELECT on market.pending_dividends to service_role;
grant SELECT on market.pending_eps_history to service_role;
grant SELECT on market.pending_filing_history to service_role;
grant SELECT on market.pending_filings to service_role;
grant SELECT on market.pending_fundamentals to service_role;
grant SELECT on market.pending_fx_history to service_role;
grant SELECT on market.pending_in_history to service_role;
grant SELECT on market.pending_in_segments to service_role;
grant SELECT on market.pending_industry to service_role;
grant SELECT on market.pending_insider to service_role;
grant SELECT on market.pending_kr_history to service_role;
grant SELECT on market.pending_kr_segments to service_role;
grant SELECT on market.pending_local_symbol to service_role;
grant SELECT on market.pending_management to service_role;
grant SELECT on market.pending_metrics to service_role;
grant SELECT on market.pending_news to service_role;
grant SELECT on market.pending_price_history to service_role;
grant SELECT on market.pending_price_targets to service_role;
grant SELECT on market.pending_prices to service_role;
grant SELECT on market.pending_profile to service_role;
grant SELECT on market.pending_profile_detail to service_role;
grant SELECT on market.pending_promotion to anon;
grant SELECT on market.pending_promotion to authenticated;
grant SELECT on market.pending_promotion to service_role;
grant SELECT on market.pending_quarters to service_role;
grant SELECT on market.pending_segment_alias to service_role;
grant SELECT on market.pending_segments to service_role;
grant SELECT on market.pending_share_stats to service_role;
grant SELECT on market.pending_statements to service_role;
grant SELECT on market.pending_symbol_repair to service_role;
grant SELECT on market.pending_ticker to service_role;
grant SELECT on market.pending_ttm to service_role;
grant SELECT on market.pending_wikidata to service_role;
grant SELECT on market.pending_xbrl to service_role;
grant SELECT on market.pending_yahoo_symbol to service_role;
grant SELECT on market.performance to anon;
grant SELECT on market.performance to authenticated;
grant SELECT on market.performance to service_role;
grant SELECT on market.price_series to anon;
grant SELECT on market.price_series to authenticated;
grant SELECT on market.price_series to service_role;
grant SELECT on market.resource_health to anon;
grant SELECT on market.resource_health to authenticated;
grant SELECT on market.resource_health to service_role;
grant SELECT on market.sector_constituents to anon;
grant SELECT on market.sector_constituents to authenticated;
grant SELECT on market.sector_constituents to service_role;
grant SELECT on market.security_currency to anon;
grant SELECT on market.security_currency to authenticated;
grant SELECT on market.security_currency to service_role;
grant SELECT on market.security_current to anon;
grant SELECT on market.security_current to authenticated;
grant SELECT on market.security_current to service_role;
grant SELECT on market.security_disclosure to anon;
grant SELECT on market.security_disclosure to authenticated;
grant SELECT on market.security_disclosure to service_role;
grant SELECT on market.security_earnings_surprise to anon;
grant SELECT on market.security_earnings_surprise to authenticated;
grant SELECT on market.security_earnings_surprise to service_role;
grant SELECT on market.security_facets to anon;
grant SELECT on market.security_facets to authenticated;
grant SELECT on market.security_facets to service_role;
grant SELECT on market.security_fundamentals_current to anon;
grant SELECT on market.security_fundamentals_current to authenticated;
grant SELECT on market.security_fundamentals_current to service_role;
grant SELECT on market.security_funds to anon;
grant SELECT on market.security_funds to authenticated;
grant SELECT on market.security_funds to service_role;
grant SELECT on market.security_industries to anon;
grant SELECT on market.security_industries to authenticated;
grant SELECT on market.security_industries to service_role;
grant SELECT on market.security_insider_summary to anon;
grant SELECT on market.security_insider_summary to authenticated;
grant SELECT on market.security_insider_summary to service_role;
grant SELECT on market.security_leadership to anon;
grant SELECT on market.security_leadership to authenticated;
grant SELECT on market.security_leadership to service_role;
grant SELECT on market.security_market_cap_usd to anon;
grant SELECT on market.security_market_cap_usd to authenticated;
grant SELECT on market.security_market_cap_usd to service_role;
grant SELECT on market.security_metric_series to anon;
grant SELECT on market.security_metric_series to authenticated;
grant SELECT on market.security_metric_series to service_role;
grant SELECT on market.security_news to anon;
grant SELECT on market.security_news to authenticated;
grant SELECT on market.security_news to service_role;
grant SELECT on market.security_next_earnings to anon;
grant SELECT on market.security_next_earnings to authenticated;
grant SELECT on market.security_next_earnings to service_role;
grant SELECT on market.security_peers to anon;
grant SELECT on market.security_peers to authenticated;
grant SELECT on market.security_peers to service_role;
grant SELECT on market.security_ratio_series to anon;
grant SELECT on market.security_ratio_series to authenticated;
grant SELECT on market.security_ratio_series to service_role;
grant SELECT on market.security_recent_filings to anon;
grant SELECT on market.security_recent_filings to authenticated;
grant SELECT on market.security_recent_filings to service_role;
grant SELECT on market.security_segment_current to anon;
grant SELECT on market.security_segment_current to authenticated;
grant SELECT on market.security_segment_current to service_role;
grant SELECT on market.security_segment_detail to anon;
grant SELECT on market.security_segment_detail to authenticated;
grant SELECT on market.security_segment_detail to service_role;
grant SELECT on market.security_segment_geography to anon;
grant SELECT on market.security_segment_geography to authenticated;
grant SELECT on market.security_segment_geography to service_role;
grant SELECT on market.security_segment_latest to anon;
grant SELECT on market.security_segment_latest to authenticated;
grant SELECT on market.security_segment_latest to service_role;
grant SELECT on market.security_segment_spine to anon;
grant SELECT on market.security_segment_spine to authenticated;
grant SELECT on market.security_segment_spine to service_role;
grant SELECT on market.security_statement_current to anon;
grant SELECT on market.security_statement_current to authenticated;
grant SELECT on market.security_statement_current to service_role;
grant SELECT on market.security_style to anon;
grant SELECT on market.security_style to authenticated;
grant SELECT on market.security_style to service_role;
grant SELECT on market.security_symbol to anon;
grant SELECT on market.security_symbol to authenticated;
grant SELECT on market.security_symbol to service_role;
grant SELECT on market.symbol_cache_classification to anon;
grant SELECT on market.symbol_cache_classification to authenticated;
grant SELECT on market.symbol_cache_classification to service_role;
grant SELECT on market.symbol_security to anon;
grant SELECT on market.symbol_security to authenticated;
grant SELECT on market.symbol_security to service_role;
grant SELECT on market.ticker_disagreement to anon;
grant SELECT on market.ticker_disagreement to authenticated;
grant SELECT on market.ticker_disagreement to service_role;
grant SELECT on market.untracked_listing to anon;
grant SELECT on market.untracked_listing to authenticated;
grant SELECT on market.untracked_listing to service_role;
grant SELECT on market.venue_currency to anon;
grant SELECT on market.venue_currency to authenticated;
grant SELECT on market.venue_currency to service_role;
